
/*
CCU8配置
*/

#include <XMC4400.h>
#include "CCU8.h"



void CCU80_Init(void)
{
	uint16_t PWM_Period=5000;
    uint16_t PWM_Compare = 5001;	
	
	WR_REG(SCU_RESET->PRSET0, SCU_RESET_PRSET0_CCU80RS_Msk, SCU_RESET_PRSET0_CCU80RS_Pos, 1);
	WR_REG(SCU_RESET->PRCLR0, SCU_RESET_PRCLR0_CCU80RS_Msk, SCU_RESET_PRCLR0_CCU80RS_Pos, 1);	
	WR_REG(SCU_CLK->CLKSET, SCU_CLK_CLKSET_CCUCEN_Msk, SCU_CLK_CLKSET_CCUCEN_Pos, 1);		
	WR_REG(CCU80->GIDLC, CCU8_GIDLC_SPRB_Msk, CCU8_GIDLC_SPRB_Pos, 1);

	WR_REG(CCU80_CC80->PSC, CCU8_CC8_PSC_PSIV_Msk, CCU8_CC8_PSC_PSIV_Pos, 0);		      //0分频
	WR_REG(CCU80_CC80->FPC, CCU8_CC8_FPC_PVAL_Pos, CCU8_CC8_FPC_PVAL_Pos, 0);	          //0分频
	WR_REG(CCU80_CC80->INS, CCU8_CC8_INS_EV0IS_Msk, CCU8_CC8_INS_EV0IS_Pos, 7);	          //与CCU8x.INyH互连
	WR_REG(CCU80_CC80->INS, CCU8_CC8_INS_EV0EM_Msk, CCU8_CC8_INS_EV0EM_Pos, 1);	          //信号在上升沿有效	
	WR_REG(CCU80_CC80->CMC, CCU8_CC8_CMC_STRTS_Msk, CCU8_CC8_CMC_STRTS_Pos, 1);	          //外部启动功能由事件 0 触发
	WR_REG(CCU80_CC80->TC, CCU8_CC8_TC_MCME1_Msk, CCU8_CC8_TC_MCME1_Pos, 1);              //使能通道 1 的多通道模式			
	WR_REG(CCU80_CC80->TC, CCU8_CC8_TC_TCM_Msk, CCU8_CC8_TC_TCM_Pos, 1);                  //中心对齐模式		
	WR_REG(CCU80_CC80->TC, CCU8_CC8_TC_STRM_Msk, CCU8_CC8_TC_STRM_Pos, 1);	              //清除定时器并将运行位置 1( 清空 / 启动 )	
	WR_REG(CCU80_CC80->DC1R, CCU8_CC8_DC1R_DT1F_Msk, CCU8_CC8_DC1R_DT1F_Pos, 60);         //下降跳变死区时间
	WR_REG(CCU80_CC80->DC1R, CCU8_CC8_DC1R_DT1R_Msk, CCU8_CC8_DC1R_DT1R_Pos, 60);         //上升跳变死区时间
	WR_REG(CCU80_CC80->DTC, CCU8_CC8_DTC_DTE1_Msk, CCU8_CC8_DTC_DTE1_Pos, 1);             //使能通道 1 的死区时间
	WR_REG(CCU80_CC80->DTC, CCU8_CC8_DTC_DCEN1_Msk, CCU8_CC8_DTC_DCEN1_Pos, 1);           //使能 CC8yST1 通路的死区时间
	WR_REG(CCU80_CC80->DTC, CCU8_CC8_DTC_DCEN2_Msk, CCU8_CC8_DTC_DCEN2_Pos, 1);           //使能反相 CC8yST1 通路的死区时间
	WR_REG(CCU80_CC80->PRS, CCU8_CC8_PRS_PRS_Msk, CCU8_CC8_PRS_PRS_Pos, PWM_Period);
	WR_REG(CCU80_CC80->CR1S, CCU8_CC8_CR1S_CR1S_Msk, CCU8_CC8_CR1S_CR1S_Pos, PWM_Compare);

	WR_REG(CCU80_CC81->PSC, CCU8_CC8_PSC_PSIV_Msk, CCU8_CC8_PSC_PSIV_Pos, 0);		
	WR_REG(CCU80_CC81->FPC, CCU8_CC8_FPC_PVAL_Pos, CCU8_CC8_FPC_PVAL_Pos, 0);	
	WR_REG(CCU80_CC81->INS, CCU8_CC8_INS_EV0IS_Msk, CCU8_CC8_INS_EV0IS_Pos, 7);	
	WR_REG(CCU80_CC81->INS, CCU8_CC8_INS_EV0EM_Msk, CCU8_CC8_INS_EV0EM_Pos, 1);		
	WR_REG(CCU80_CC81->CMC, CCU8_CC8_CMC_STRTS_Msk, CCU8_CC8_CMC_STRTS_Pos, 1);	
	WR_REG(CCU80_CC81->TC, CCU8_CC8_TC_MCME1_Msk, CCU8_CC8_TC_MCME1_Pos, 1);	
	WR_REG(CCU80_CC81->TC, CCU8_CC8_TC_TCM_Msk, CCU8_CC8_TC_TCM_Pos, 1);		
	WR_REG(CCU80_CC81->TC, CCU8_CC8_TC_STRM_Msk, CCU8_CC8_TC_STRM_Pos, 1);
	WR_REG(CCU80_CC81->DC1R, CCU8_CC8_DC1R_DT1F_Msk, CCU8_CC8_DC1R_DT1F_Pos, 60);
	WR_REG(CCU80_CC81->DC1R, CCU8_CC8_DC1R_DT1R_Msk, CCU8_CC8_DC1R_DT1R_Pos, 60);
	WR_REG(CCU80_CC81->DTC, CCU8_CC8_DTC_DTE1_Msk, CCU8_CC8_DTC_DTE1_Pos, 1);
	WR_REG(CCU80_CC81->DTC, CCU8_CC8_DTC_DCEN1_Msk, CCU8_CC8_DTC_DCEN1_Pos, 1);
	WR_REG(CCU80_CC81->DTC, CCU8_CC8_DTC_DCEN2_Msk, CCU8_CC8_DTC_DCEN2_Pos, 1);
	WR_REG(CCU80_CC81->PRS, CCU8_CC8_PRS_PRS_Msk, CCU8_CC8_PRS_PRS_Pos, PWM_Period);
	WR_REG(CCU80_CC81->CR1S, CCU8_CC8_CR1S_CR1S_Msk, CCU8_CC8_CR1S_CR1S_Pos, PWM_Compare);
   
	WR_REG(CCU80_CC82->PSC, CCU8_CC8_PSC_PSIV_Msk, CCU8_CC8_PSC_PSIV_Pos, 0);		
	WR_REG(CCU80_CC82->FPC, CCU8_CC8_FPC_PVAL_Pos, CCU8_CC8_FPC_PVAL_Pos, 0);	
	WR_REG(CCU80_CC82->INS, CCU8_CC8_INS_EV0IS_Msk, CCU8_CC8_INS_EV0IS_Pos, 7);	
	WR_REG(CCU80_CC82->INS, CCU8_CC8_INS_EV0EM_Msk, CCU8_CC8_INS_EV0EM_Pos, 1);		
	WR_REG(CCU80_CC82->CMC, CCU8_CC8_CMC_STRTS_Msk, CCU8_CC8_CMC_STRTS_Pos, 1);	
	WR_REG(CCU80_CC82->TC, CCU8_CC8_TC_MCME1_Msk, CCU8_CC8_TC_MCME1_Pos, 1);	
	WR_REG(CCU80_CC82->TC, CCU8_CC8_TC_TCM_Msk, CCU8_CC8_TC_TCM_Pos, 1);
	WR_REG(CCU80_CC82->TC, CCU8_CC8_TC_STRM_Msk, CCU8_CC8_TC_STRM_Pos, 1);
	WR_REG(CCU80_CC82->DC1R, CCU8_CC8_DC1R_DT1F_Msk, CCU8_CC8_DC1R_DT1F_Pos, 60);
	WR_REG(CCU80_CC82->DC1R, CCU8_CC8_DC1R_DT1R_Msk, CCU8_CC8_DC1R_DT1R_Pos, 60);
	WR_REG(CCU80_CC82->DTC, CCU8_CC8_DTC_DTE1_Msk, CCU8_CC8_DTC_DTE1_Pos, 1);
	WR_REG(CCU80_CC82->DTC, CCU8_CC8_DTC_DCEN1_Msk, CCU8_CC8_DTC_DCEN1_Pos, 1);
	WR_REG(CCU80_CC82->DTC, CCU8_CC8_DTC_DCEN2_Msk, CCU8_CC8_DTC_DCEN2_Pos, 1);
	WR_REG(CCU80_CC82->PRS, CCU8_CC8_PRS_PRS_Msk, CCU8_CC8_PRS_PRS_Pos, PWM_Period);
	WR_REG(CCU80_CC82->CR1S, CCU8_CC8_CR1S_CR1S_Msk, CCU8_CC8_CR1S_CR1S_Pos, PWM_Compare);
	
	WR_REG(CCU80_CC80->INTE, CCU8_CC8_INTE_OME_Msk, CCU8_CC8_INTE_OME_Pos, 1);
	WR_REG(CCU80_CC80->SRS, CCU8_CC8_SRS_POSR_Msk, CCU8_CC8_SRS_POSR_Pos, 0);     //1匹配触发CCU8中断

	WR_REG(CCU80->GCSS, CCU8_GCSS_S0SE_Msk, CCU8_GCSS_S0SE_Pos, 1);
	WR_REG(CCU80->GCSS, CCU8_GCSS_S1SE_Msk, CCU8_GCSS_S1SE_Pos, 1);	
	WR_REG(CCU80->GCSS, CCU8_GCSS_S2SE_Msk, CCU8_GCSS_S2SE_Pos, 1);	
	
	WR_REG(CCU80->GIDLC, CCU8_GIDLC_CS0I_Msk, CCU8_GIDLC_CS0I_Pos, 1);
	WR_REG(CCU80->GIDLC, CCU8_GIDLC_CS1I_Msk, CCU8_GIDLC_CS1I_Pos, 1);
	WR_REG(CCU80->GIDLC, CCU8_GIDLC_CS2I_Msk, CCU8_GIDLC_CS2I_Pos, 1);
}


void CCU80_Start(void)
{
	WR_REG(SCU_GENERAL->CCUCON, SCU_GENERAL_CCUCON_GSC80_Msk, SCU_GENERAL_CCUCON_GSC80_Pos, 1);
}

void POSIF0_Init(void)
{
	WR_REG(SCU_RESET->PRSET0, SCU_RESET_PRSET0_POSIF0RS_Msk, SCU_RESET_PRSET0_POSIF0RS_Pos, 1);
	WR_REG(SCU_RESET->PRCLR0, SCU_RESET_PRCLR0_POSIF0RS_Msk, SCU_RESET_PRCLR0_POSIF0RS_Pos, 1);	
	WR_REG(SCU_CLK->CLKSET, SCU_CLK_CLKSET_CCUCEN_Msk, SCU_CLK_CLKSET_CCUCEN_Pos, 1);
	
    WR_REG(POSIF0->PCONF, POSIF_PCONF_INSEL0_Msk, POSIF_PCONF_INSEL0_Pos, 0);//A，POSIF.IN0A 1.1
	WR_REG(POSIF0->PCONF, POSIF_PCONF_INSEL1_Msk, POSIF_PCONF_INSEL1_Pos, 0);//B，POSIF.IN1A 1.2
	WR_REG(POSIF0->PCONF, POSIF_PCONF_INSEL2_Msk, POSIF_PCONF_INSEL2_Pos, 0);//Z，POSIF.IN2A 1.3
	
    WR_REG(POSIF0->PCONF, POSIF_PCONF_FSEL_Msk, POSIF_PCONF_FSEL_Pos, 3);	 //正交编码器模式
	WR_REG(POSIF0->PCONF, POSIF_PCONF_QDCM_Msk, POSIF_PCONF_QDCM_Pos, 0);    //标准正交模式
	WR_REG(POSIF0->PCONF, POSIF_PCONF_MCUE_Msk, POSIF_PCONF_MCUE_Pos, 1);    //软件控制多通道序列更新
	
	WR_REG(POSIF0->QDC, POSIF_QDC_PALS_Msk, POSIF_QDC_PALS_Pos, 0);          //A有效高电平
	WR_REG(POSIF0->QDC, POSIF_QDC_PBLS_Msk, POSIF_QDC_PBLS_Pos, 0);          //B有效高电平
	WR_REG(POSIF0->QDC, POSIF_QDC_PHS_Msk, POSIF_QDC_PHS_Pos, 1);            //A超前为顺时针旋转
	WR_REG(POSIF0->QDC, POSIF_QDC_ICM_Msk, POSIF_QDC_ICM_Pos, 2);            //每次Z信号都在POSIF.OUT3产生索引标志
	WR_REG(POSIF0->QDC, POSIF_QDC_DVAL_Msk, POSIF_QDC_DVAL_Pos, 1);          //顺时针方向旋转
	
	WR_REG(POSIF0->PFLGE, POSIF_PFLGE_EINDX_Msk, POSIF_PFLGE_EINDX_Pos, 1);  //索引中断启用
	WR_REG(POSIF0->PFLGE, POSIF_PFLGE_INDSEL_Msk, POSIF_PFLGE_INDSEL_Pos, 0);//服务请求线
	
	WR_REG(POSIF0->PRUNS, POSIF_PRUNS_SRB_Msk, POSIF_PRUNS_SRB_Pos, 1);      //POSIF启用
}

void Switch_off(void)
{
	WR_REG(POSIF0->MCSM, POSIF_MCSM_MCMPS_Msk, POSIF_MCSM_MCMPS_Pos, 0x000);
	WR_REG(POSIF0->MCMS, POSIF_MCMS_STMR_Msk, POSIF_MCMS_STMR_Pos, 1);
}

void Switch_on(void)
{
	WR_REG(POSIF0->MCSM, POSIF_MCSM_MCMPS_Msk, POSIF_MCSM_MCMPS_Pos, 0x333);
	WR_REG(POSIF0->MCMS, POSIF_MCMS_STMR_Msk, POSIF_MCMS_STMR_Pos, 1);
}
