
/*
GPIO 
*/

#include <XMC1300.h>
#include "SCU.h"

void SCU_Init(void)
{
	SCU_GENERAL->PASSWD =
				((0x0 << SCU_GENERAL_PASSWD_MODE_Pos) & SCU_GENERAL_PASSWD_MODE_Msk) |          
				((0x18 << SCU_GENERAL_PASSWD_PASS_Pos) & SCU_GENERAL_PASSWD_PASS_Msk); 	
	
    WR_REG(SCU_CLK->CGATCLR0, SCU_CLK_CGATCLR0_CCU40_Msk, SCU_CLK_CGATCLR0_CCU40_Pos, 1);      //CCU4 це©ь
	WR_REG(SCU_CLK->CGATCLR0, SCU_CLK_CGATCLR0_VADC_Msk, SCU_CLK_CGATCLR0_VADC_Pos, 1);        //VADC це©ь
	WR_REG(SCU_CLK->CGATCLR0, SCU_CLK_CGATCLR0_USIC0_Msk, SCU_CLK_CGATCLR0_USIC0_Pos, 1);      //USIC це©ь
	
	WR_REG(SCU_CLK->CLKCR, SCU_CLK_CLKCR_IDIV_Msk, SCU_CLK_CLKCR_IDIV_Pos, 1);                 //MCLK 32M
	WR_REG(SCU_CLK->CLKCR, SCU_CLK_CLKCR_PCLKSEL_Msk, SCU_CLK_CLKCR_PCLKSEL_Pos, 1);           //PCLK 64M
	
	SCU_GENERAL->PASSWD =
				((0x3 << SCU_GENERAL_PASSWD_MODE_Pos) & SCU_GENERAL_PASSWD_MODE_Msk) |          
				((0x18 << SCU_GENERAL_PASSWD_PASS_Pos) & SCU_GENERAL_PASSWD_PASS_Msk); 
}


