#include "POSIF.h"

void POSIF0_Init(void)
{
	WR_REG(SCU_RESET->PRSET0, SCU_RESET_PRSET0_POSIF0RS_Msk, SCU_RESET_PRSET0_POSIF0RS_Pos, 1);
	WR_REG(SCU_RESET->PRCLR0, SCU_RESET_PRCLR0_POSIF0RS_Msk, SCU_RESET_PRCLR0_POSIF0RS_Pos, 1);	
	WR_REG(SCU_CLK->CLKSET, SCU_CLK_CLKSET_CCUCEN_Msk, SCU_CLK_CLKSET_CCUCEN_Pos, 1);
	
    WR_REG(POSIF0->PCONF, POSIF_PCONF_INSEL0_Msk, POSIF_PCONF_INSEL0_Pos, 1);//A，POSIF.IN0B 14.7
	WR_REG(POSIF0->PCONF, POSIF_PCONF_INSEL1_Msk, POSIF_PCONF_INSEL1_Pos, 1);//B，POSIF.IN1B 14.6
	WR_REG(POSIF0->PCONF, POSIF_PCONF_INSEL2_Msk, POSIF_PCONF_INSEL2_Pos, 1);//Z，POSIF.IN2B 14.5
	
    WR_REG(POSIF0->PCONF, POSIF_PCONF_FSEL_Msk, POSIF_PCONF_FSEL_Pos, 3);	 //正交编码器模式
	WR_REG(POSIF0->PCONF, POSIF_PCONF_QDCM_Msk, POSIF_PCONF_QDCM_Pos, 0);    //标准正交模式
	WR_REG(POSIF0->PCONF, POSIF_PCONF_MCUE_Msk, POSIF_PCONF_MCUE_Pos, 1);    //软件控制多通道序列更新
	
	WR_REG(POSIF0->QDC, POSIF_QDC_PALS_Msk, POSIF_QDC_PALS_Pos, 0);          //A有效高电平
	WR_REG(POSIF0->QDC, POSIF_QDC_PBLS_Msk, POSIF_QDC_PBLS_Pos, 0);          //B有效高电平
	WR_REG(POSIF0->QDC, POSIF_QDC_PHS_Msk, POSIF_QDC_PHS_Pos, 1);            //A超前为顺时针旋转
	WR_REG(POSIF0->QDC, POSIF_QDC_ICM_Msk, POSIF_QDC_ICM_Pos, 2);            //每次Z信号都在POSIF.OUT3产生索引标志
	WR_REG(POSIF0->QDC, POSIF_QDC_DVAL_Msk, POSIF_QDC_DVAL_Pos, 1);          //顺时针方向旋转
	
	WR_REG(POSIF0->PFLGE, POSIF_PFLGE_EINDX_Msk, POSIF_PFLGE_EINDX_Pos, 1);  //索引中断启用
	WR_REG(POSIF0->PFLGE, POSIF_PFLGE_INDSEL_Msk, POSIF_PFLGE_INDSEL_Pos, 0);//服务请求线
	
	WR_REG(POSIF0->PRUNS, POSIF_PRUNS_SRB_Msk, POSIF_PRUNS_SRB_Pos, 1);      //POSIF启用	
}
